# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xm7YwYz4QcPF17XyNQjPHDtg5jMQ35Zo
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st
from textblob import TextBlob

# Title
st.title("📝 Sentiment Analysis NLP App")
st.subheader("Analyze the sentiment of your text in real-time")

# Text Input
user_input = st.text_area("Enter your text here:")

if st.button("Analyze"):
    if user_input.strip() != "":
        blob = TextBlob(user_input)
        sentiment_score = blob.sentiment.polarity

        # Display sentiment result
        if sentiment_score > 0:
            st.success(f"🙂 Positive Sentiment (Score: {sentiment_score:.2f})")
        elif sentiment_score < 0:
            st.error(f"☹️ Negative Sentiment (Score: {sentiment_score:.2f})")
        else:
            st.warning(f"😐 Neutral Sentiment (Score: {sentiment_score:.2f})")
    else:
        st.warning("⚠️ Please enter some text before analyzing.")